"""rename_email_column

Revision ID: 1cdce7151613
Revises: 791279dd0760
Create Date: 2024-02-10 18:51:45.195325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cdce7151613'
down_revision = '791279dd0760'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('new_email', sa.String(length=55), nullable=True))
    op.drop_column('students', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('email', sa.VARCHAR(length=55), nullable=True))
    op.drop_column('students', 'new_email')
    # ### end Alembic commands ###
